import '../styles/globals.css'
import '../styles/markdown-github.css'
import siteConfig from '../config/site.config'

import ClientLayout from './_components/client-layout'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="OneDrive Vercel Index" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        {siteConfig.googleFontLinks.map(link => (
          <link key={link} rel="stylesheet" href={link} />
        ))}
      </head>
      <body>
      <ClientLayout>
      {children}
      </ClientLayout>
      </body>
    </html>
  )
}
